<a href="https://colab.research.google.com/github/kseniia308/Hausaufgaben/blob/task2/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [ ]:
np.pad(np.zeros((8, 8)), pad_width = 1, constant_values = 1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [ ]:
np.tile( np.array([[0,1], [1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [ ]:
np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [ ]:
arr = np.random.random((5, 5))
arr - np.reshape(np.mean(arr, 1), (5, 1))


array([[-0.13434146,  0.00573625,  0.1273978 ,  0.17090748, -0.16970007],
       [ 0.2293787 ,  0.17467839, -0.20876007, -0.46215761,  0.26686059],
       [ 0.35647682,  0.45021897, -0.47672775,  0.20626166, -0.53622968],
       [-0.36123644,  0.40268719,  0.00901017, -0.09690721,  0.04644629],
       [ 0.09200052,  0.03996677, -0.14502049, -0.28825636,  0.30130956]])

Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [ ]:
arr = np.random.rand(10, 3)
np.choose(np.argmin(abs(arr - 0.5), 1), arr.T)

array([0.30606362, 0.70976738, 0.50489298, 0.47237286, 0.36604341,
       0.7222632 , 0.44195538, 0.48312436, 0.55132594, 0.54115638])

Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [ ]:
arr = np.random.rand(6, 6)
np.sum(arr, axis = 1)/np.choose(np.argmax(arr, 0), arr)

array([2.45679308, 4.03631921, 5.95826967, 2.66459496, 3.09072326,
       2.06646255])

На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max(np.take(x, (np.where(x == 0)[0] + 1)[: -1]))



5

Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [ ]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
np.add.at(x, i, 1)
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
